### ISSUE TITLE
adjustments in User_Setup.h of TFT_eSPI library missing in description

### ISSUE THREAD

**Issue by dp2008** [bmellink/GeigerCounter#1]
Had strange lines on display and screen was rotated, found out that adjustment in User_Setup.h of TFT_eSPI library was missing:

comment #define ILI9341_DRIVER
-> //#define ILI9341_DRIVER

uncomment //#define ST7789_DRIVER      // Full configuration option, define additional parameters below for this display
-> #define ST7789_DRIVER      // Full configuration option, define additional parameters below for this display

with these adjustments it works.

**Comment by bmellink** [comment]
Thanks. I updated the readme
